# Generated by Django 2.2.4 on 2019-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('nome_autor', models.CharField(max_length=50)),
                ('assunto', models.CharField(max_length=50)),
                ('editora', models.CharField(max_length=50)),
                ('ISBN', models.IntegerField(max_length=15)),
                ('ano_publicacao', models.DateField()),
            ],
        ),
    ]
